<%
local_db_username = ENV["RUBY_SERVICE_DATABASE_USERNAME"].presence
local_db_password = ENV["RUBY_SERVICE_DATABASE_PASSWORD"].presence
local_db_host = ENV["RUBY_SERVICE_DATABASE_HOST"].presence
local_db_port = ENV["RUBY_SERVICE_DATABASE_PORT"].presence
%>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ruby_service_development

test:
  primary: &primary_test
    <<: *default
    database: ruby_service_test
<% if local_db_username %>
    username: <%= local_db_username %>
<% end %>
<% if local_db_password %>
    password: <%= local_db_password %>
<% end %>
<% if local_db_host %>
    host: <%= local_db_host %>
<% end %>
<% if local_db_port %>
    port: <%= local_db_port %>
<% end %>
  queue:
    <<: *primary_test
    database: ruby_service_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: ruby_service_production
    username: ruby_service
    password: <%= ENV["RUBY_SERVICE_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("RUBY_SERVICE_DATABASE_HOST", "127.0.0.1") %>
    port: <%= ENV.fetch("RUBY_SERVICE_DATABASE_PORT", 5432) %>
  cache:
    <<: *primary_production
    database: ruby_service_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ruby_service_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ruby_service_production_cable
    migrations_paths: db/cable_migrate
