if(NOT DEFINED VG_FLASH_SIZE_BYTES OR NOT DEFINED VG_PROTECTED_TAIL_BYTES)
  message(FATAL_ERROR "persistent flash check requires flash and protected-tail sizes")
endif()

if(DEFINED VG_IMAGE_END)
  set(VG_ACTUATOR_PERSISTENT_IMAGE_END "${VG_IMAGE_END}")
else()
  if(NOT DEFINED VG_NM OR NOT DEFINED VG_ELF)
    message(FATAL_ERROR "persistent flash check requires VG_NM/VG_ELF or VG_IMAGE_END")
  endif()
  execute_process(
    COMMAND "${VG_NM}" -n "${VG_ELF}"
    RESULT_VARIABLE VG_ACTUATOR_PERSISTENT_NM_RESULT
    OUTPUT_VARIABLE VG_ACTUATOR_PERSISTENT_NM_OUTPUT
    ERROR_VARIABLE VG_ACTUATOR_PERSISTENT_NM_ERROR
  )
  if(NOT VG_ACTUATOR_PERSISTENT_NM_RESULT EQUAL 0)
    message(FATAL_ERROR "persistent flash check could not inspect ${VG_ELF}: ${VG_ACTUATOR_PERSISTENT_NM_ERROR}")
  endif()
  string(REGEX MATCH "([0-9A-Fa-f]+)[ \t]+[A-Za-z][ \t]+__flash_binary_end"
         VG_ACTUATOR_PERSISTENT_END_MATCH "${VG_ACTUATOR_PERSISTENT_NM_OUTPUT}")
  if(NOT VG_ACTUATOR_PERSISTENT_END_MATCH)
    message(FATAL_ERROR "persistent flash check could not find __flash_binary_end in ${VG_ELF}")
  endif()
  set(VG_ACTUATOR_PERSISTENT_IMAGE_END "0x${CMAKE_MATCH_1}")
endif()

math(EXPR VG_ACTUATOR_PERSISTENT_JOURNAL_BASE
     "0x10000000 + ${VG_FLASH_SIZE_BYTES} - ${VG_PROTECTED_TAIL_BYTES}")
math(EXPR VG_ACTUATOR_PERSISTENT_IMAGE_END_VALUE "${VG_ACTUATOR_PERSISTENT_IMAGE_END}")
if(VG_ACTUATOR_PERSISTENT_IMAGE_END_VALUE GREATER VG_ACTUATOR_PERSISTENT_JOURNAL_BASE)
  message(FATAL_ERROR
    "${VG_LABEL}: firmware overlaps reserved persistent flash: image end=${VG_ACTUATOR_PERSISTENT_IMAGE_END_VALUE}, journal base=${VG_ACTUATOR_PERSISTENT_JOURNAL_BASE}")
endif()
math(EXPR VG_ACTUATOR_PERSISTENT_HEADROOM
     "${VG_ACTUATOR_PERSISTENT_JOURNAL_BASE} - ${VG_ACTUATOR_PERSISTENT_IMAGE_END_VALUE}")
message(STATUS
  "${VG_LABEL}: persistent tail check passed (image end=${VG_ACTUATOR_PERSISTENT_IMAGE_END_VALUE}, journal base=${VG_ACTUATOR_PERSISTENT_JOURNAL_BASE}, headroom=${VG_ACTUATOR_PERSISTENT_HEADROOM} bytes)")
